import { Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  footerContainer: {
    position: "absolute",
    bottom: 25,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    borderTopStyle: "solid",
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  disclaimer: {
    fontSize: 7,
    color: "#6b7280",
    maxWidth: "80%",
    lineHeight: 1.3,
  },
  pageNumber: {
    fontSize: 8,
    color: "#6b7280",
  },
});

export default function PDFFooter() {
  return (
    <View style={styles.footerContainer} fixed>
      <Text style={styles.disclaimer}>
        Disclaimer: This tailored resume was generated by Resume Shapeshifter. The user is responsible for verifying all content for accuracy before submitting it to any employer.
      </Text>
      <Text
        style={styles.pageNumber}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}
